### ISSUE TITLE
I updated the script as an extension with SD Webui 1.5 and now it fails. I can't figure out why.

### ISSUE THREAD

**Issue by 1busyguy** [Animator-Anon/animator_extension#1]
When I add an initial image and start the generation, it produces a output folder but then this appears in the console.

![error_msg_animator](https://user-images.githubusercontent.com/807880/216527801-3dba1027-41d8-4761-af13-02f85c713673.PNG)

**Comment by Animator-Anon** [comment]
Ugh I dunno, are you running the latest webUI? Some kind of problem with applying the styles to the templates...
Looks like you have not selected a template, prompt or a style. That shouldn't matter. Do you have any styles defined at all in the webUI? If not, try create one, maybe that's where the issue lies.

**Comment by Animator-Anon** [comment]
Either way I added an error handler around the styles application, hope that helps.

**Comment by sujitrulz** [comment]
I am facing the same error.. Do we have a fix now?

**Comment by Animator-Anon** [comment]
Have you tried the current version?

**Comment by Animator-Anon** [comment]
Still broken?
