### ISSUE TITLE
use of keyframes. 

### ISSUE THREAD

**Issue by 1busyguy** [Animator-Anon/animator_extension#6]
Would it be possible for you to elaborate on the configuration of these key frame prompts, with maybe 2 examples of end results.
I have been do experiments  to get the desired results, yet you expertise may aid in the learning curve.  thx.
Wonderful software!

**Comment by Animator-Anon** [comment]
More than what is in the readme in this repository? Which ones do you feel are under documented, I'll try flesh it out.

**Comment by 1busyguy** [comment]
**time_s | source | video, images, img2img | path**
( provide examples for video/images )

_For multiple video/Image transitions would it be:_

0 | source | images | c:\animation\images\img01.png
0 | prompt | large black dog | cat
10 | source | images | c:\animation\images\img02.png
10 | prompt | large white dog | cat
20 | source | images | c:\animation\images\img03.png
20 | prompt | large spotted dog | cat
30 | source | images | c:\animation\images\img04.png
30 | prompt | large sheep dog | cat

0 | source | video | c:\animation\images\vid01.mp4
0 | prompt | large black dog | cat
10 | source | video | c:\animation\images\vid02.mp4
10 | prompt | large white dog | cat
20 | source | video | c:\animation\images\vid03.mp4
20 | prompt | large spotted dog | cat
30 | source | video | c:\animation\images\vid04.mp4
30 | prompt | large sheep dog | cat

OR:

**time_s | prompt_from_png | file_path**
( provide examples for images )

_For multiple PNG images transitions would it be:_

0 | source | prompt_from_png | c:\animation\images\img01.png
0 | prompt | large black dog | cat
10 | source | prompt_from_png | c:\animation\images\img02.png
10 | prompt | large white dog | cat
20 | source | prompt_from_png | c:\animation\images\img03.png
20 | prompt | large spotted dog | cat
30 | source | prompt_from_png | c:\animation\images\img04.png
30 | prompt | large sheep dog | cat

**Comment by Animator-Anon** [comment]
That is some crazy usage there.

A few points, I don't think you can add more than one source. If you try and add an additional source, it will should overwrite the first one. Same applies for a video or a folder full of images.
The idea using images as a source, is you would put in a folder and file mask, such as c:\animation\images\img*.png, and would find a list of files that match that mask. It would use these as source frames. When it comes to rendering frame 5, it will grab the fifth image out of that alphabetically sorted list and use that as the source frame, rather than using the loopback img2img frame.
You should have more or the same number of frames in that folder than the animation you want to create, otherwise it keep using the end frame if it runs out.
Similarly, with a video source, it would grab the fifth frame from the video and use that as the source image.


You have the syntax wrong for the prompt_from_png line. You need to replace the parts in italics.
_time_s_ | prompt_from_png | _file_path_
it should be like this:
30 | prompt_from_png | c:\animation\images\img04.png

All the keyframes start with the fame time as a floating point number, the command, than a variable number of parameters.


If you use a prompt_from_png and a prompt keyframe for the same time, I don't know what would happen without trying. I suspect only one will apply or you will get an error. It isn't something I planned for.
All that happens when you load the prompt from a file is it reads the png info, and will set the seed, positive and negative prompts to match what are in the png file. It doesn't load the image and set it. There are a bunch of other parameters that go into making a picture what it is, such as the model, denoising, config scale etc etc.

If you wanted to set the image, you could try use the prop keyframe to get it to draw a new image over the top in the frame's post production.

I am working on adding more examples, it takes time though. I will try to add examples that detail how things are intended to work. Some features I added were because I was trying stuff out, and they aren't particularly useful, unfortunately. I kept them in because this is more of a toolbox to automate some stuff in the webUI.
